apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microcenter-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Optional: specify a storage class if needed
  # storageClassName: standard
